services:
  postgres:
    image: postgres:16
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5

  redis:
    image: redis:7
    restart: always

  api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: .
    command: celery -A app.worker.celery_app worker --loglevel=info
    env_file: .env
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  bot:
    build: .
    command: python -u bot/handler.py
    env_file: .env
    depends_on:
      api:
        condition: service_started

volumes:
  postgres_data:
