"""add_content_field_to_news_items

Revision ID: 65d4d955c335
Revises: d0272b9ca89b
Create Date: 2025-08-04 20:13:42.858043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d4d955c335'
down_revision: Union[str, Sequence[str], None] = 'd0272b9ca89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_items', sa.Column('content', sa.Text(), nullable=True, comment='Full article content'))
    op.add_column('news_items', sa.Column('summary', sa.Text(), nullable=True, comment='LLM-generated summary'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_items', 'summary')
    op.drop_column('news_items', 'content')
    # ### end Alembic commands ###
