"""add languages table and fk on subscription

Revision ID: d0272b9ca89b
Revises: d3f636478692
Create Date: 2025-07-31 21:26:16.860560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0272b9ca89b'
down_revision: Union[str, Sequence[str], None] = 'd3f636478692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.alter_column('subscriptions', 'language',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='Language code for summaries (ISO 639-1)',
               existing_nullable=False)
    op.create_foreign_key(None, 'subscriptions', 'languages', ['language'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.alter_column('subscriptions', 'language',
               existing_type=sa.VARCHAR(length=8),
               comment='Language code for summaries (ISO 639-1)',
               existing_nullable=False)
    op.drop_table('languages')
    # ### end Alembic commands ###
